### ISSUE TITLE
environment version

### ISSUE THREAD

**Issue by xiaobh1519** [longyunf/radiant#11]
Thanks for your great work! Could you please offer the version list of your package for envrionment and may I ask whether you run it on RTX20xx or 30xx?  Thanks for your attention!

**Comment by longyunf** [comment]
python 3.7
ubuntu 22.04
pytorch 1.9.0 
cuda 11.1

I install pytorch with:
conda install pytorch torchvision cudatoolkit=11.1 -c pytorch -c nvidia -y

and mmdet3d with:
git clone https://github.com/open-mmlab/mmdetection3d.git
cd mmdetection3d
git checkout v0.16.0
pip install -v -e .
