### ISSUE TITLE
Problem of trainning 

### ISSUE THREAD

**Issue by YuJiXYZ** [longyunf/radiant#12]
![image](https://github.com/longyunf/radiant/assets/106587670/40ae2a2e-3183-4dea-b70e-28a1de7a9684)
When I train this step, but get a result of following, can someone help me to solve this.
Thank you very much~!!!!!
![image](https://github.com/longyunf/radiant/assets/106587670/3a2f91b1-26fb-4a93-aa22-753d66a9ea6c)

**Comment by longyunf** [comment]
I think the mmcv version you are using has a problem with the dump function. You can simply comment the line 'cfg.dump(out_path)' as it is used to save configurations and has no influence on training.

**Comment by YuJiXYZ** [comment]
ok，thank you~
