### ISSUE TITLE
question about running pgd val and test code!

### ISSUE THREAD

**Issue by MinHsuan123** [longyunf/radiant#4]
I finished training and want to val and test my model, but when it's finished, it doesn't show any mAP info!! only json, but I open json file,it look like this 
![Screenshot from 2023-07-14 20-49-04](https://github.com/longyunf/radiant/assets/139560105/c12ca6b7-ab2c-423f-9bc8-f3ad52962203)
how can I know how much is mAP for my model? 
Thank you

**Comment by longyunf** [comment]
The evaluation code saves performance as metrics_summary.json in the folder out_dir. The code also prints a summary of performance. See
https://github.com/longyunf/radiant/blob/cf5355396d42ef17940e29ef8f9e3cabfd8035c3/scripts/train_radiant_pgd.py#L397C1-L400

**Comment by stanny880913** [comment]
![Screenshot from 2023-07-17 16-27-09](https://github.com/longyunf/radiant/assets/56072246/b1c53cbc-c9e3-451b-a646-c69bfa5c2bed)

This is the results when I ran `CUDA_VISIBLE_DEVICES=0 python scripts/train_radiant_pgd.py --do_eval --eval_set test`，it did not show the  summary of performance，why this happened?!

![Screenshot from 2023-07-17 16-27-35](https://github.com/longyunf/radiant/assets/56072246/fa6d6ccb-0412-47db-a4a7-c2285435592b)
 and the folder only had one json, no metrics_summary.json!!
 how can I fixed it~
 thank you

**Comment by longyunf** [comment]
The evaluation is not conducted locally because there is no ground truth publicly available for test set. It is supposed to be conducted on nuScenes evaluation server with the generated result file.

**Comment by stanny880913** [comment]
> The evaluation is not conducted locally because there is no ground truth publicly available for test set. It is supposed to be conducted on nuScenes evaluation server with the generated result file.

I can understand，and I found Nuscenes eval_ai，is this website you use to caculate mAP，Is the nuScenes detection challenge a challenge you participated in before? so I need to update `results_nusc.json` on the challenge，right ?
![image](https://github.com/longyunf/radiant/assets/56072246/554d5d0d-6dc1-4dbd-b17c-6819aefe9880)
but the results look like all Null，or this situation is normal? it's look like no bbox are detected !!
thank you

**Comment by longyunf** [comment]
Yes. You need to zip the result file generated by evaluation code and submit it to the challenge.

**Comment by MinHsuan123** [comment]
> Yes. You need to zip the result file generated by evaluation code and submit it to the challenge.

Sorry, but I ran the --eval test and always show the results like above!!!

> > The evaluation is not conducted locally because there is no ground truth publicly available for test set. It is supposed to be conducted on nuScenes evaluation server with the generated result file.
> 
> I can understand，and I found Nuscenes eval_ai，is this website you use to caculate mAP，Is the nuScenes detection challenge a challenge you participated in before? so I need to update `results_nusc.json` on the challenge，right ? ![image](https://user-images.githubusercontent.com/56072246/254465014-554d5d0d-6dc1-4dbd-b17c-6819aefe9880.png) but the results look like all Null，or this situation is normal? it's look like no bbox are detected !! thank you

How can I fix it? is there any parameters need to set up? or something went wrong?
Thank you
